# Generated by Django 6.1 on 2026-08-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="page_count",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
